### PR TITLE
The Unlicense

### PR DESCRIPTION
**Pull request by lschmierer**

### CODE REVIEW

**Comment by ebkalderon** [comment]
I'm fine with the Unlicense myself, but it looks like there was some disagreement on Gitter. What do others think about this?

**Comment by lschmierer** [comment]
We can simply use MIT/Apache here, too.
But Apache requires to "state changes". I don't know what implications for closed-source projects it has.

**Comment by lschmierer** [comment]
Apache does NOT require to state changes (http://www.apache.org/foundation/license-faq.html#Must-Contribute).
So I would suggest sticking to the standard: MIT an Apache 2

**Comment by ebkalderon** [comment]
Sounds reasonable. Should we close this pull request and open a new one? I'd recommend the filenames `LICENSE-MIT` and `LICENSE-APACHE` when dual-licensing.

**Pull request merged**
